### ISSUE TITLE
关于data中polygons中的图形

### ISSUE THREAD

**Issue by XniniD** [reso1/MCFS#1]
请问polygons文件中的关于多边形的文件，比如A.plg，是怎么得到的呢？拜读了这篇代码但仍然找不到答案，希望作者百忙之中能回答我的问题，将感激不尽！

**Comment by reso1** [comment]
Hi @XniniD, thanks for your great feedback! Each polygon file (.plg) is actually a [shapely Polygon](https://shapely.readthedocs.io/en/stable/reference/shapely.Polygon.html) object stored using pickle. So you can read the doc and create your own .plg instance.

**Comment by XniniD** [comment]
Hello, sorry to bother you again. How can I solve the problem of errors like those shown in the picture? Moreover, when using the A * algorithm, there may be errors where the points are not in the graph. How can this be resolved? If you could answer my question, I would greatly appreciate it
<img width="761" alt="屏幕截图 2024-05-24 163803" src="https://github.com/reso1/MCFS/assets/133486493/6830747b-8387-42ef-bbeb-8ee86b289a41">
![屏幕截图 2024-05-24 164544](https://github.com/reso1/MCFS/assets/133486493/06afdf85-946f-4a9b-a18c-dd8fd4463665)

**Comment by reso1** [comment]
The problem seems to be too general for me to answer. I suggest you debug and check what points and on which isoline they are not in the graph, and then see where they come from since all the sampled points of the isolines should be in the graph for pathfinding.
